const copy={
en:{
 title:'Lucas Arana — Beyond Borders',meta:'Explore Lucas Arana’s world: engineering, people and operations connecting Latin America with US teams.',
 connectLinkedIn:'Connect with me on LinkedIn',connectShort:'Connect ↗',role:'Software engineer & COO',tagline:'Software engineer & COO',myStory:'My story ↗',language:'Cambiar a español',sound:'SOUND',soundOn:'Turn sound on',soundOff:'Turn sound off',help:'Help and controls',
 eyebrow:'BUENOS AIRES ROOTS. A BORDERLESS MINDSET.',heroEnd:'BEYOND BORDERS.',intro:'I’m Lucas. Software engineer &amp; COO at Nexton.<br> I build the operation that connects Latin American engineers with US teams.',enter:'Explore my world',loading:'Building the world',duration:'A PLAYABLE JOURNEY THROUGH MY WORK',introCredit:'BUILT IN ARGENTINA <span>·</span> CONNECTED TO THE WORLD',worldName:'THE WORLD OF',worldTag:'PEOPLE. SYSTEMS. POSSIBILITIES.',
 missionKicker:'YOUR MISSION / CONNECT MY WORLD',missionTitle:'Connect the three LATAM hubs.',missionDescription:'Visit an island, discover a part of my work and activate its connection.',reset:'Restart mission',connections:'{count} / 3 CONNECTIONS',ready:'READY TO FLY',flying:'FLYING TO {place}',landed:'TOUCHDOWN',manual:'MANUAL PILOT',
 missionUS:'Bring the connection to the US.',missionUSDescription:'Three hubs connected. One final destination.',missionComplete:'Mission complete. People connected.',missionCompleteDescription:'You’ve explored my world. Let’s talk about what we could build together.',completeStatus:'MISSION COMPLETE',
 notes:'FIELD NOTES BY LUCAS ARANA',closeDiscovery:'Close field notes',connected:'CONNECTED',connectionEstablished:'CONNECTION ESTABLISHED / {place}',oneLess:'One less border.',allConnected:'Three LATAM hubs connected. Take the team to the US to complete the mission.',nextConnection:'The route to Nexton is live. Your next connection is in {place}.',toUS:'Connect with the United States ↗',nextHub:'Explore the next hub ↗',finishUS:'Complete the US connection ↗',flyNext:'Fly to the next hub ↗',continueLATAM:'Continue in LATAM ↗',
 pilot:'Pilot',camera:'Drag to orbit · Scroll to zoom',overview:'World view ↗',flyTo:'FLY TO',flyLabel:'Fly to {place}',footer:'AN INTERACTIVE PERSONAL PORTFOLIO',corridor:'LATAM TALENT <span>↔</span> US TEAMS',
 fallbackTitle:'This world needs 3D graphics.',fallbackBody:'Open it in a recent version of Chrome, Edge or Safari with graphics acceleration enabled.',fallbackProfile:'Meet Lucas ↗',closeProfile:'Close profile',
 profileKicker:'THE PERSON BEHIND THE CONNECTIONS',profileTitle:'Engineer by training.<br><span>Operator by practice.</span>',profileBody:'I’m Lucas Arana, Software engineer &amp; COO at Nexton, based in Buenos Aires. I lead operations, talent strategy and revenue operations — the systems that make distributed engineering teams work.',profileBelief:'I treat hiring as an operations problem. Engineers vetting engineers. AI doing the first pass. Humans keeping score.',
 chapter1:'MY BASE',chapter1Body:'Buenos Aires, Argentina. Where I live and host AI Builders LATAM: operators sharing what they actually built with AI.',chapter2:'MY WORK',chapter2Body:'At Nexton since 2019. Talent, operations and the day-to-day work of connecting LATAM engineers with US companies.',chapter3:'MY SCOREBOARD',chapter3Body:'Fill rate, offer acceptance, time to hire, retention and compensation. Outcomes measured together.',
 factEngineers:'engineers placed by Nexton in US teams',factCompanies:'companies hiring through Nexton',source:'Company figures from <a href="https://nexton.dev" target="_blank" rel="noopener">Nexton ↗</a>. Personal story from <a href="https://lucasarana.com/writing/#about" target="_blank" rel="noopener">my website ↗</a>. The islands are a playful interpretation of the region.',talk:'Connect with me ↗',readNotes:'Read my writing ↗',
 manualKicker:'FLIGHT MANUAL / 01',manualTitle:'Make yourself at home.',manualBody:'<strong>Your mission:</strong> visit Argentina, Brazil and Mexico, activate each hub, then fly to the US. Each stop reveals a different part of my work.',manualList:'<li><strong>Click a destination</strong> to fly on autopilot.</li><li><strong>WASD or arrow keys</strong> to pilot the ship.</li><li><strong>Drag the world</strong> to rotate the camera.</li><li><strong>Scroll</strong> to zoom in or out.</li><li>On mobile, use the destination buttons.</li>',manualSound:'Sound is off by default. Turn it on in the top bar.',understood:'Got it. Let’s fly ↗',closeHelp:'Close help',
 completeKicker:'MISSION COMPLETE / ALL SYSTEMS CONNECTED',completeTitle:'You’ve seen my world.<br><span>Let’s build what’s next.</span>',completeBody:'Argentina is home. LATAM is the talent. The US is the connection.<br>My work is making that connection last.',contact:'Connect with me ↗',keepExploring:'Keep exploring',backWorld:'Back to the world',
 usName:'UNITED STATES',usSub:'NEW YORK / OPPORTUNITY',mexicoName:'MEXICO',mexicoSub:'YUCATÁN / SHARED WORKING DAY',brasilName:'BRAZIL',brasilSub:'RIO DE JANEIRO / PEOPLE',buenosairesName:'ARGENTINA',buenosairesSub:'BUENOS AIRES / MY HOME',nextonName:'NEXTON',nextonSub:'MY OPERATING SYSTEM',
 },
es:{
 title:'Lucas Arana — Más allá de las fronteras',meta:'Explorá el mundo de Lucas Arana: ingeniería, personas y operaciones que conectan Latinoamérica con equipos de Estados Unidos.',
 connectLinkedIn:'Conectá conmigo en LinkedIn',connectShort:'Conectá ↗',role:'Ingeniero de software & COO',tagline:'Ingeniero de software & COO',myStory:'Mi historia ↗',language:'Switch to English',sound:'SONIDO',soundOn:'Activar sonido',soundOff:'Desactivar sonido',help:'Ayuda y controles',
 eyebrow:'RAÍCES EN BUENOS AIRES. MIRADA SIN FRONTERAS.',heroEnd:'SIN FRONTERAS.',intro:'Soy Lucas. Ingeniero de software y COO de Nexton.<br> Construyo la operación que conecta ingenieros de Latinoamérica con equipos de Estados Unidos.',enter:'Explorá mi mundo',loading:'Preparando el mundo',duration:'UN VIAJE JUGABLE POR MI TRABAJO',introCredit:'HECHO EN ARGENTINA <span>·</span> CONECTADO AL MUNDO',worldName:'EL MUNDO DE',worldTag:'PERSONAS. SISTEMAS. POSIBILIDADES.',
 missionKicker:'TU MISIÓN / CONECTAR MI MUNDO',missionTitle:'Conectá los tres hubs de LATAM.',missionDescription:'Visitá una isla, descubrí una parte de mi trabajo y activá su conexión.',reset:'Reiniciar misión',connections:'{count} / 3 CONEXIONES',ready:'LISTOS PARA VOLAR',flying:'VOLANDO A {place}',landed:'ATERRIZAJE COMPLETO',manual:'PILOTO MANUAL',missionUS:'Llevá la conexión a Estados Unidos.',missionUSDescription:'Tres hubs conectados. Un último destino.',missionComplete:'Misión completa. Personas conectadas.',missionCompleteDescription:'Ya recorriste mi mundo. Hablemos de lo que podríamos construir juntos.',completeStatus:'MISIÓN COMPLETA',
 notes:'NOTAS DE VIAJE DE LUCAS ARANA',closeDiscovery:'Cerrar notas',connected:'CONECTADO',connectionEstablished:'CONEXIÓN ESTABLECIDA / {place}',oneLess:'Una frontera menos.',allConnected:'Los tres hubs de LATAM están conectados. Llevá el equipo a Estados Unidos para completar la misión.',nextConnection:'La ruta hasta Nexton está activa. Tu siguiente conexión te espera en {place}.',toUS:'Conectar con Estados Unidos ↗',nextHub:'Explorar el próximo hub ↗',finishUS:'Completar la conexión con US ↗',flyNext:'Volar al próximo hub ↗',continueLATAM:'Continuar en LATAM ↗',
 pilot:'Pilotear',camera:'Arrastrá para orbitar · Rueda para acercar',overview:'Vista general ↗',flyTo:'VOLÁ A',flyLabel:'Volar a {place}',footer:'UN PORTFOLIO PERSONAL INTERACTIVO',corridor:'TALENTO LATAM <span>↔</span> EQUIPOS DE US',
 fallbackTitle:'Este mundo necesita gráficos 3D.',fallbackBody:'Abrilo en una versión actual de Chrome, Edge o Safari con aceleración gráfica.',fallbackProfile:'Conocer a Lucas ↗',closeProfile:'Cerrar perfil',profileKicker:'LA PERSONA DETRÁS DE LAS CONEXIONES',profileTitle:'Ingeniero de formación.<br><span>Operador en la práctica.</span>',profileBody:'Soy Lucas Arana, ingeniero de software y COO de Nexton, desde Buenos Aires. Lidero operaciones, estrategia de talento y revenue operations: los sistemas que hacen funcionar a los equipos de ingeniería distribuidos.',profileBelief:'Trato la contratación como un problema de operaciones. Ingenieros evaluando ingenieros. IA haciendo el primer pase. Humanos midiendo el resultado.',chapter1:'MI BASE',chapter1Body:'Buenos Aires, Argentina. Donde vivo y organizo AI Builders LATAM: operadores compartiendo lo que realmente construyeron con IA.',chapter2:'MI TRABAJO',chapter2Body:'En Nexton desde 2019. Talento, operaciones y el trabajo diario de conectar ingenieros de LATAM con empresas de Estados Unidos.',chapter3:'MIS MÉTRICAS',chapter3Body:'Cobertura de vacantes, aceptación de ofertas, tiempo de contratación, retención y compensación. Resultados medidos en conjunto.',factEngineers:'ingenieros incorporados por Nexton a equipos de US',factCompanies:'empresas que contratan con Nexton',source:'Cifras de la empresa: <a href="https://nexton.dev" target="_blank" rel="noopener">Nexton ↗</a>. Historia personal: <a href="https://lucasarana.com/writing/#about" target="_blank" rel="noopener">mi sitio ↗</a>. Las islas son una interpretación lúdica de la región.',talk:'Conectá conmigo ↗',readNotes:'Leé lo que escribo ↗',
 manualKicker:'MANUAL DE VUELO / 01',manualTitle:'Estás en tu casa.',manualBody:'<strong>Tu misión:</strong> visitá Argentina, Brasil y México, activá cada hub y después volá a Estados Unidos. Cada parada revela una parte de mi trabajo.',manualList:'<li><strong>Hacé clic en un destino</strong> para activar el piloto automático.</li><li><strong>WASD o flechas</strong> para pilotear la nave.</li><li><strong>Arrastrá el mundo</strong> para girar la cámara.</li><li><strong>Rueda del mouse</strong> para acercarte o alejarte.</li><li>En celular, usá los botones de destino.</li>',manualSound:'El sonido empieza apagado. Podés activarlo arriba.',understood:'Entendido. A volar ↗',closeHelp:'Cerrar ayuda',completeKicker:'MISIÓN COMPLETA / TODO CONECTADO',completeTitle:'Ya conocés mi mundo.<br><span>Construyamos lo que viene.</span>',completeBody:'Argentina es mi casa. LATAM es el talento. US es la conexión.<br>Mi trabajo es hacer que esa conexión dure.',contact:'Conectá conmigo ↗',keepExploring:'Seguir explorando',backWorld:'Volver al mundo',
 usName:'ESTADOS UNIDOS',usSub:'NUEVA YORK / OPORTUNIDAD',mexicoName:'MÉXICO',mexicoSub:'YUCATÁN / EL MISMO HORARIO',brasilName:'BRASIL',brasilSub:'RÍO DE JANEIRO / PERSONAS',buenosairesName:'ARGENTINA',buenosairesSub:'BUENOS AIRES / MI CASA',nextonName:'NEXTON',nextonSub:'MI SISTEMA OPERATIVO',
 }
};
const stories={
 en:{
 buenosaires:{kicker:'01 / BUENOS AIRES, ARGENTINA',title:'Home is where I build.',body:'I’m based in Buenos Aires. Software engineering shaped how I think; operations is where I apply it. I also host AI Builders LATAM here, bringing together operators who share what they actually shipped.',action:'Connect engineering judgment ↗'},
 brasil:{kicker:'02 / RIO DE JANEIRO, BRAZIL',title:'People before profiles.',body:'At Nexton, engineers vet engineers. I care about the judgment behind a résumé: who can own a system, collaborate with a team and catch an AI model when it is wrong. That is the human connection I work to protect.',action:'Connect the people ↗'},
 mexico:{kicker:'03 / YUCATÁN, MEXICO',title:'Great work happens together.',body:'I write about why timezone overlap matters more as AI writes more code. The human work is reviewing, deciding and catching mistakes together. A shared working day is part of the operation I build.',action:'Connect the working day ↗'},
 us:{kicker:'04 / UNITED STATES',title:'The connection is the beginning.',body:'My job does not end at a hire. At Nexton we run the operation behind embedded engineering teams: contracts, payroll and talent health. Connect the LATAM hubs first, then bring that operation here.',action:'Continue in LATAM ↗'},
 nexton:{kicker:'NEXTON / MY OPERATING SYSTEM',title:'I connect the dots.',body:'I joined Nexton in 2019. Today, as COO, I lead operations, talent strategy and revenue operations. The real scoreboard: fill rate, offer acceptance, time to hire, retention and compensation — read together.',action:'Meet the person behind it ↗'}
 },
 es:{
 buenosaires:{kicker:'01 / BUENOS AIRES, ARGENTINA',title:'Mi casa. Mi punto de partida.',body:'Vivo en Buenos Aires. La ingeniería de software formó mi manera de pensar; las operaciones son donde la aplico. También organizo AI Builders LATAM acá, reuniendo a operadores que comparten lo que realmente construyeron.',action:'Conectar criterio técnico ↗'},
 brasil:{kicker:'02 / RÍO DE JANEIRO, BRASIL',title:'Personas antes que perfiles.',body:'En Nexton, ingenieros evalúan a ingenieros. Me importa el criterio detrás del CV: quién puede hacerse cargo de un sistema, colaborar y detectar cuándo una IA se equivoca. Esa es la conexión humana que busco cuidar.',action:'Conectar a las personas ↗'},
 mexico:{kicker:'03 / YUCATÁN, MÉXICO',title:'El buen trabajo se hace juntos.',body:'Escribo sobre por qué compartir horario importa más cuando la IA escribe más código. El trabajo humano es revisar, decidir y detectar errores juntos. Compartir la jornada es parte de la operación que construyo.',action:'Conectar la jornada ↗'},
 us:{kicker:'04 / ESTADOS UNIDOS',title:'La conexión es el comienzo.',body:'Mi trabajo no termina con una contratación. En Nexton sostenemos la operación detrás de los equipos: contratos, pagos y bienestar del talento. Primero conectá los hubs de LATAM y después traé esa operación hasta acá.',action:'Continuar en LATAM ↗'},
 nexton:{kicker:'NEXTON / MI SISTEMA OPERATIVO',title:'Conecto los puntos.',body:'Me sumé a Nexton en 2019. Hoy, como COO, lidero operaciones, estrategia de talento y revenue operations. Mis métricas: cobertura de vacantes, aceptación de ofertas, tiempo de contratación, retención y compensación, leídas en conjunto.',action:'Conocer a la persona detrás ↗'}
 }
};
const bindings={'.identity small':'tagline','#profile-open':'myStory','.sound-label':'sound','.intro-copy>.eyebrow':'eyebrow','#world-title>span':'heroEnd','.intro-description':'intro','.journey-length':'duration','.world-name>span':'worldName','.world-name>small':'worldTag','.mission-top>.eyebrow':'missionKicker','.flight-hint>span:nth-child(2)':'pilot','.flight-hint>span:nth-of-type(3)':'camera','#overview':'overview','.destination-prefix':'flyTo','.footer-center':'corridor','.world-footer>span:last-child':'footer','#fallback h2':'fallbackTitle','#fallback p':'fallbackBody','#fallback-profile':'fallbackProfile','#help-dialog>.eyebrow':'manualKicker','#help-dialog h2':'manualTitle','#help-dialog>p:first-of-type':'manualBody','#help-dialog ul':'manualList','#help-dialog>p:last-of-type':'manualSound','#help-dialog>.primary':'understood','#complete-dialog>.eyebrow':'completeKicker','#complete-dialog h2':'completeTitle','#complete-dialog>p':'completeBody','#complete-dialog .primary':'contact','#keep-exploring':'keepExploring'};
for(const [selector,key] of Object.entries(bindings)){document.querySelector(selector)?.setAttribute('data-i18n',key);}
const ariaBindings={'#menu-open':'help','#reset':'reset','#discovery-close':'closeDiscovery','#help-dialog>.close-button':'closeHelp','#complete-dialog>.close-button':'backWorld'};
for(const [selector,key] of Object.entries(ariaBindings)){document.querySelector(selector)?.setAttribute('data-i18n-label',key);}
let language='en';try{if(localStorage.getItem('lucas-world-language')==='es')language='es';}catch{}
export const getLanguage=()=>language;
export const t=(key,values={})=>{let text=copy[language][key]??copy.en[key]??key;for(const [k,v] of Object.entries(values))text=text.replaceAll('{'+k+'}',String(v));return text;};
export const story=id=>stories[language][id];
export const stationLabel=id=>t(id+'Name');
export function applyLanguage(){document.documentElement.lang=language;document.title=t('title');document.querySelector('meta[name="description"]').content=t('meta');document.querySelectorAll('[data-i18n]').forEach(el=>{el.innerHTML=t(el.dataset.i18n);});document.querySelectorAll('[data-i18n-label]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nLabel)));const b=document.getElementById('language');b.textContent=language==='en'?'EN / ES':'ES / EN';b.setAttribute('aria-label',t('language'));}
export function setLanguage(next){language=next==='es'?'es':'en';try{localStorage.setItem('lucas-world-language',language);}catch{}applyLanguage();}
